openapi: 3.1.0
info:
  title: ""
  version: ""
components:
  schemas:
    FileMetadata:
      type: object
      properties:
        name:
          type: string
        path:
          type: string
        size:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        modifiedAt:
          type: string
          format: date-time
        checksum:
          description: e.g., SHA256
          type: string
        isDirectory:
          type: boolean
